### ISSUE TITLE
License? FF port

### ISSUE THREAD

**Issue by Soneji** [ShantnuS/oof-on-close#1]
Hi,

I am looking to port this to Firefox. I was wondering whether you had a license for the software so I can modify it and create a FF pull request. 

I assume you are using the sound effect from 'http://www.orangefreesounds.com/roblox-death-sound/' which says 'The sound effect is permitted for commercial use under license Creative Commons Attribution 4.0 International License' 

So you could add any open source license to the repo but just in the README you could write oof.mp3 is licensed under the Creative Commons Attribution 4.0 International License [https://creativecommons.org/licenses/by/4.0/] with a link to the license. 

This is a really cool project and I love using it on Chrome - just wanted to port it to ff as well as I am switching browsers now for privacy reasons. :)

**Comment by Soneji** [comment]
Update: I just had a go at running it on FF and it seems to work perfectly out of the box. Would you like me to package it and put it on the FF addons store?

**Comment by ShantnuS** [comment]
Sure dude go for it!

I'll add license information to the repo when I get the time :)
________________________________

**Comment by Soneji** [comment]
Legend. By the way, I recommend GPL 2/3 or MIT.

**Comment by Soneji** [comment]
Hello,

Your add-on, Oof! 1.1.1, has been approved and is now available for download in our gallery at https://addons.mozilla.org/addon/roblox_oof/

Developer Resources

**Comment by Soneji** [comment]
added PR for the ff link #2

**Comment by ShantnuS** [comment]
Merged and added license :)
